### ISSUE TITLE
Add ability to login via API

### ISSUE THREAD

**Issue by shevtsod** [matryoshkadoll/matryoshka-app#15]
We now have a basic API set up on the server that allows users to login. We would like to begin writing our Android app by first implementing an activity that allows users to enter their credentials and have an authentication token stored on the app for use in future requests.

We would ideally want to have this ready for the next presentation on Feb 8.

@oscar666666 will handle this as discussed in our meeting on Jan 25.

**Comment by oscar666666** [comment]
#18 
done
